import { NextResponse } from 'next/server';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
async function supa(path:string,method:string,body:any){if(!url||!key) return {ok:false,missing:true}; return fetch(`${url}/rest/v1/${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)});}
export async function POST(req:Request){try{const b=await req.json();const userId=b.userId??null;const date=b.date??new Date().toISOString().slice(0,10);
 if(b.type==='habit'){const r=await supa('myos_habit_logs','POST',{user_id:userId,habit_key:b.habitKey,habit:b.habitKey,log_date:date,completed:Boolean(b.completed)});if(!r.ok)return NextResponse.json({ok:false,mode:r.missing?'not_configured':'error',detail:await r.text()},{status:r.missing?200:r.status});}
 if(b.type==='daily'){const r=await supa('myos_daily_logs','POST',{user_id:userId,log_date:date,execution_score:b.executionScore??0,completed_tasks:b.completedTasks??0,total_tasks:b.totalTasks??0,completed_habits:b.completedHabits??0,total_habits:b.totalHabits??0,available_minutes:b.availableMinutes??null,energy:b.energy??null,next_action:b.nextAction??null});if(!r.ok)return NextResponse.json({ok:false,mode:r.missing?'not_configured':'error',detail:await r.text()},{status:r.missing?200:r.status});}
 if(b.type==='learning'){const r=await supa('myos_learning_activities','POST',{user_id:userId,activity_date:date,skill:b.skill,activity_type:b.activityType??'practice',title:b.title,rating:b.rating??null,estimated_minutes:b.estimatedMinutes??null,actual_minutes:b.actualMinutes??null,xp_earned:b.xp??0,xp:b.xp??0,deliverable:b.deliverable??null,project_name:b.projectName??null,status:b.status??'completed',metadata:b.metadata??{}});if(!r.ok)return NextResponse.json({ok:false,mode:r.missing?'not_configured':'error',detail:await r.text()},{status:r.missing?200:r.status});}
 return NextResponse.json({ok:true});}catch(e){return NextResponse.json({ok:false,detail:e instanceof Error?e.message:'Invalid payload'},{status:400})}}
