'use client'

import { useEffect, useState } from 'react'

const starters = ['What should I focus on today based on my MYOS data?','Analyze my current bottleneck and give me the next 3 actions.','Turn my current work into a learning + portfolio + content plan.']

type Decision = { title:string; summary:string; bottleneck:string; focus:string; actions:{title:string;why:string;minutes:number;priority:string}[]; learning_action:{skill:string;task:string;minutes:number}; portfolio_action:{title:string;proof:string}; content_action:{title:string;platform:string;angle:string}; risks:string[] }

export default function AICorePage() {
  const [message,setMessage]=useState(''),[answer,setAnswer]=useState(''),[loading,setLoading]=useState(false),[decisionLoading,setDecisionLoading]=useState(false),[error,setError]=useState(''),[sessionId,setSessionId]=useState<string|null>(null),[decision,setDecision]=useState<Decision|null>(null)
  useEffect(()=>{fetch('/api/myos/decision-engine').then(r=>r.json()).then(d=>{if(d.ok&&d.decisions?.[0])setDecision(d.decisions[0])}).catch(()=>{})},[])
  async function ask(text=message){const prompt=text.trim();if(!prompt||loading)return;setLoading(true);setError('');setAnswer('');try{const res=await fetch('/api/myos/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:prompt,sessionId})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||'AI Core request failed');setAnswer(data.text);if(data.sessionId)setSessionId(data.sessionId)}catch(e){setError(e instanceof Error?e.message:'AI Core request failed')}finally{setLoading(false)}}
  async function runDecision(){if(decisionLoading)return;setDecisionLoading(true);setError('');try{const res=await fetch('/api/myos/decision-engine',{method:'POST'});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||'Decision engine failed');setDecision(data.decision)}catch(e){setError(e instanceof Error?e.message:'Decision engine failed')}finally{setDecisionLoading(false)}}
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="mark">M</span><div><b>MYOS</b><small>Control Panel</small></div></div>{['Today','Site OS','Work','Learning','Projects','Portfolio','Content','Habits','Finance','AI Core'].map(item=><button key={item} className={item==='AI Core'?'nav active':'nav'} onClick={()=>{if(item==='Today')window.location.href='/'}}>{item}</button>)}<div className="side-foot">AI Core · Decision Layer</div></aside><section className="content"><header className="top"><div><p className="eyebrow">MYOS INTELLIGENCE</p><h1>AI Core</h1><p className="muted">Think → Decide → Execute → Learn → Prove → Publish.</p></div><button className="nav active" onClick={runDecision} disabled={decisionLoading}>{decisionLoading?'Analyzing…':'Run Today’s Decision'}</button></header>
    {decision&&<div className="card hero"><span>LIVE DECISION ENGINE</span><h2>{decision.title}</h2><p className="muted">{decision.summary}</p><div className="grid main-grid"><div className="practice-box"><b>Focus</b><br/>{decision.focus||'—'}</div><div className="practice-box"><b>Bottleneck</b><br/>{decision.bottleneck||'—'}</div><div className="practice-box"><b>Learning</b><br/>{decision.learning_action?.skill||'—'} · {decision.learning_action?.minutes||0} min</div></div><h3>Next actions</h3>{decision.actions?.map((a,i)=><div className="practice-box" key={i}><b>{i+1}. {a.title}</b><p className="muted">{a.why} · {a.minutes} min · {a.priority}</p></div>)}<div className="grid main-grid"><div className="practice-box"><b>Portfolio proof</b><br/>{decision.portfolio_action?.title||'—'}<p className="muted">{decision.portfolio_action?.proof||''}</p></div><div className="practice-box"><b>Content</b><br/>{decision.content_action?.title||'—'}<p className="muted">{decision.content_action?.platform||''} · {decision.content_action?.angle||''}</p></div></div></div>}
    <div className="card hero"><span>AI DECISION LAYER</span><h2>What should MYOS help you decide?</h2><p className="muted">AI Core now reads your authenticated MYOS operating data instead of relying on a static prompt.</p><div className="grid main-grid">{starters.map(s=><button key={s} className="practice-box" onClick={()=>{setMessage(s);ask(s)}}>{s}</button>)}</div></div><div className="card"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask MYOS anything about your work, learning, projects, execution or next decision..." rows={5}/><div style={{display:'flex',gap:12,marginTop:12}}><button className="nav active" onClick={()=>ask()} disabled={loading}>{loading?'Thinking…':'Ask AI Core'}</button><button className="nav" onClick={()=>{setMessage('');setAnswer('');setError('');setSessionId(null)}}>New Session</button></div></div>{error&&<div className="card"><h3>AI Core error</h3><p className="muted">{error}</p></div>}{answer&&<div className="card"><span className="label">🧠 DECISION</span><div style={{whiteSpace:'pre-wrap',lineHeight:1.7}}>{answer}</div></div>}</section></main>
}
